-- create schema
CREATE SCHEMA ampad;

-- The table that contains all entity ID from ampad project
CREATE TABLE ampad.ENTITY_ID AS
SELECT DISTINCT ID FROM warehouse.NODE_SNAPSHOT WHERE PROJECT_ID = 2580853;

-- tables that are created once

CREATE TABLE ampad.DOWNLOAD (
USER_ID BIGINT(20),
SUCCESS BOOLEAN,
CLIENT enum('R','PYTHON','WEB','JAVA','COMMAND_LINE','ELB_HEALTHCHECKER','UNKNOWN'),
MONTH CHAR(3),
ENTITY_ID BIGINT(20)
);

CREATE TABLE ampad.VIEW (
USER_ID BIGINT(20),
CLIENT enum('R','PYTHON','WEB','JAVA','COMMAND_LINE','ELB_HEALTHCHECKER','UNKNOWN'),
MONTH CHAR(3),
ENTITY_ID BIGINT(20)
);
