-- create schema
CREATE SCHEMA ampad;

-- The table that contains all entity ID from ampad project
CREATE TABLE ampad.ENTITY_ID AS
SELECT DISTINCT ID FROM warehouse.NODE_SNAPSHOT WHERE PROJECT_ID = 2580853;

SELECT * FROM ampad.ENTITY_ID;

-- The table that contains all activities from Mar 10 to Apr 1
CREATE TABLE ampad.AR_MAR AS
SELECT DISTINCT AR.TIMESTAMP, AR.SESSION_ID, AR.ELAPSE_MS, AR.USER_ID, AR.RETURN_OBJECT_ID, AR.SUCCESS, AR.RESPONSE_STATUS, 
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM warehouse.ACCESS_RECORD AR, warehouse.PROCESSED_ACCESS_RECORD PAR
WHERE AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.TIMESTAMP BETWEEN 1425945600000 AND (1427846400000 - 1);

SELECT COUNT(*) FROM ampad.AR_MAR WHERE RETURN_OBJECT_ID IN (SELECT * FROM ampad.ENTITY_ID);

-- The table that contains all activities in ampad project from Mar 10 to end of Mar
CREATE TABLE ampad.ACTIVITIES_MAR AS
SELECT * FROM ampad.AR_MAR
WHERE ENTITY_ID IN (SELECT * FROM ampad.ENTITY_ID);

SELECT * FROM ampad.ACTIVITIES_MAR;

-- The table that contains all activities from Apr 1 to May 1
CREATE TABLE ampad.AR_APR AS
SELECT DISTINCT AR.TIMESTAMP, AR.SESSION_ID, AR.ELAPSE_MS, AR.USER_ID, AR.RETURN_OBJECT_ID, AR.SUCCESS, AR.RESPONSE_STATUS, 
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM warehouse.ACCESS_RECORD AR, warehouse.PROCESSED_ACCESS_RECORD PAR
WHERE AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.TIMESTAMP BETWEEN 1427846400000 AND (1430438400000 - 1);

-- The table that contains all activities in ampad project from Apr 1 to May 1
CREATE TABLE ampad.ACTIVITIES_APR AS
SELECT * FROM ampad.AR_APR
WHERE ENTITY_ID IN (SELECT * FROM ampad.ENTITY_ID);

-- The table that contains all activities from May 1 to Jun 1
CREATE TABLE ampad.AR_MAY AS
SELECT DISTINCT AR.TIMESTAMP, AR.SESSION_ID, AR.ELAPSE_MS, AR.USER_ID, AR.RETURN_OBJECT_ID, AR.SUCCESS, AR.RESPONSE_STATUS, 
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM warehouse.ACCESS_RECORD AR, warehouse.PROCESSED_ACCESS_RECORD PAR
WHERE AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.TIMESTAMP BETWEEN 1430438400000 AND (1433116800000 - 1);

-- The table that contains all activities in ampad project from May 1 to Jun 1
CREATE TABLE ampad.ACTIVITIES_MAY AS
SELECT * FROM ampad.AR_MAY
WHERE ENTITY_ID IN (SELECT * FROM ampad.ENTITY_ID);

-- The table that contains all activities from JUN 1 to JUL 1
CREATE TABLE ampad.AR_JUN AS
SELECT DISTINCT AR.TIMESTAMP, AR.SESSION_ID, AR.ELAPSE_MS, AR.USER_ID, AR.RETURN_OBJECT_ID, AR.SUCCESS, AR.RESPONSE_STATUS, 
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM warehouse.ACCESS_RECORD AR, warehouse.PROCESSED_ACCESS_RECORD PAR
WHERE AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.TIMESTAMP BETWEEN 1433116800000 AND (1435708800000 - 1);

-- The table that contains all activities in ampad project from JUN 1 to JUL 1
CREATE TABLE ampad.ACTIVITIES_JUN AS
SELECT * FROM ampad.AR_JUN
WHERE ENTITY_ID IN (SELECT * FROM ampad.ENTITY_ID);

-- The table that contains all activities from JUL 1 to AUG 1
CREATE TABLE ampad.AR_JUL AS
SELECT DISTINCT AR.TIMESTAMP, AR.SESSION_ID, AR.ELAPSE_MS, AR.USER_ID, AR.RETURN_OBJECT_ID, AR.SUCCESS, AR.RESPONSE_STATUS, 
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM warehouse.ACCESS_RECORD AR, warehouse.PROCESSED_ACCESS_RECORD PAR
WHERE AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.TIMESTAMP BETWEEN 1435708800000 AND (1438387200000 - 1);

-- The table that contains all activities in ampad project from JUL 1 to AUG 1
CREATE TABLE ampad.ACTIVITIES_JUL AS
SELECT * FROM ampad.AR_JUL
WHERE ENTITY_ID IN (SELECT * FROM ampad.ENTITY_ID);

-- The table that contains all activities from AUG 1 to SEP 1
CREATE TABLE ampad.AR_AUG AS
SELECT DISTINCT AR.TIMESTAMP, AR.SESSION_ID, AR.ELAPSE_MS, AR.USER_ID, AR.RETURN_OBJECT_ID, AR.SUCCESS, AR.RESPONSE_STATUS, 
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM warehouse.ACCESS_RECORD AR, warehouse.PROCESSED_ACCESS_RECORD PAR
WHERE AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.TIMESTAMP BETWEEN 1438387200000 AND (1441065600000 - 1);

-- The table that contains all activities in ampad project from AUG 1 to SEP 1
CREATE TABLE ampad.ACTIVITIES_AUG AS
SELECT * FROM ampad.AR_AUG
WHERE ENTITY_ID IN (SELECT * FROM ampad.ENTITY_ID);

-- The table that contains all activities from SEP 1 to OCT 1
CREATE TABLE ampad.AR_SEP AS
SELECT DISTINCT AR.TIMESTAMP, AR.SESSION_ID, AR.ELAPSE_MS, AR.USER_ID, AR.RETURN_OBJECT_ID, AR.SUCCESS, AR.RESPONSE_STATUS, 
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM warehouse.ACCESS_RECORD AR, warehouse.PROCESSED_ACCESS_RECORD PAR
WHERE AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.TIMESTAMP BETWEEN 1441065600000 AND (1443657600000 - 1);

-- The table that contains all activities in ampad project from SEP 1 to OCT 1
CREATE TABLE ampad.ACTIVITIES_SEP AS
SELECT * FROM ampad.AR_SEP
WHERE ENTITY_ID IN (SELECT * FROM ampad.ENTITY_ID);

-- The table that contains all activities from OCT 1 to NOV 1
CREATE TABLE ampad.AR_OCT AS
SELECT DISTINCT AR.TIMESTAMP, AR.SESSION_ID, AR.ELAPSE_MS, AR.USER_ID, AR.RETURN_OBJECT_ID, AR.SUCCESS, AR.RESPONSE_STATUS, 
PAR.ENTITY_ID, PAR.CLIENT, PAR.NORMALIZED_METHOD_SIGNATURE
FROM warehouse.ACCESS_RECORD AR, warehouse.PROCESSED_ACCESS_RECORD PAR
WHERE AR.SESSION_ID = PAR.SESSION_ID
AND AR.TIMESTAMP = PAR.TIMESTAMP
AND AR.TIMESTAMP BETWEEN 1443657600000 AND (1446336000000 - 1);

-- The table that contains all activities in ampad project from OCT 1 to NOV 1
CREATE TABLE ampad.ACTIVITIES_OCT AS
SELECT * FROM ampad.AR_OCT
WHERE ENTITY_ID IN (SELECT * FROM ampad.ENTITY_ID);
